# config/packages/knp_snappy.yaml

knp_snappy:
    pdf:
        enabled: true
        binary: '%env(WKHTMLTOPDF_PATH)%' # Chemin vers l'exécutable wkhtmltopdf
        options: []
    image:
        enabled: true
        binary: '%env(WKHTMLTOIMAGE_PATH)%' # Chemin vers l'exécutable wkhtmltoimage
        options: []
