controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_login:
    path: /
    controller: App\Controller\SecurityController::login


devis_download:
    path: '/devis/{id}/download'
    controller: 'App\Controller\DevisController::downloadPdf'
